### ISSUE TITLE
Does somebody use in MacOS Ventura 13.3? 

### ISSUE THREAD

**Issue by dz14Skll** [m-inan/mac-translate#1]
I passed the privacy filter by "Open anyway" and the app is open, but no window opened. In the Menu Bar, when the app is active, I cannot display preferences or anything else as a dropdown menu. 

I don't understand what I'm doing wrong. Is there a shortcut to activate a window? in a similar way to opening Spotlight? 

Thanks!

**Comment by dz14Skll** [comment]
Sorry! I've already seen the shortcut 😅 ( Cmd + } ) 

Works perfectly 👍

**Comment by sickerin** [comment]
I'm actually facing the same issue, upon opening it. Nothing shows up no windows. I tried all the shortcut listed nothing happens. I'm on Mac OS 13.1 Apple Silicon

**Comment by m-inan** [comment]
Hi @sickerin, default keyboard shortcut is `CMD + \`. You can see screenshot down below.

![shortcut](https://github.com/m-inan/mac-translate/assets/25525515/2dd7e3ea-8eb8-47af-8d7e-525e1241f7a3)

**Comment by m-inan** [comment]
I'm using Intel Mac. If it is not working for you, you can try manually in code.

> AppDelegate.swift
```swift
class AppDelegate: NSObject, NSApplicationDelegate {
  ...

  func applicationDidFinishLaunching(_ aNotification: Notification) {
    ...

    // Add this two line bottom of the method
    panel.isPresented = true
    panel.makeKeyAndOrderFront(nil)
  }

  ...
}
```

**Comment by sickerin** [comment]
Hi @m-inan thanks it works. Great app! I believe you have it wrong on the readme. It says `CMD + /` instead of  `CMD + \`, just fyi. 

Also, I think it would be great if when it's first opened/ we click `translate.app` the window is shown, instead of being hidden. Plus maybe having `?` button that will show the shortcuts will make it more user-friendly. I can try to work on it since I'm interested in doing some Mac app dev.
